FROM alpine:3.8

ENV TZ=Europe/Moscow

RUN apk add --no-cache sqlite tzdata

# Alpine comes with built in cron schedules
# min   hour    day     month   weekday command
# */15    *       *       *       *       run-parts /etc/periodic/15min
# 0       *       *       *       *       run-parts /etc/periodic/hourly
# 0       2       *       *       *       run-parts /etc/periodic/daily
# 0       3       *       *       6       run-parts /etc/periodic/weekly
# 0       5       1       *       *       run-parts /etc/periodic/monthly

# Place script in appropriate folder
#COPY backup_db.sh /etc/periodic/hourly
COPY backupdb /etc/periodic/hourly

# bash-4.4# crond --help
# BusyBox v1.28.4 (2018-05-30 10:45:57 UTC) multi-call binary.
# Usage: crond -fbS -l N -d N -L LOGFILE -c DIR
#        -f      Foreground
#        -b      Background (default)
#        -S      Log to syslog (default)
#        -l N    Set log level. Most verbose 0, default 8
#        -d N    Set log level, log to stderr
#        -L FILE Log to FILE
#        -c DIR  Cron dir. Default:/var/spool/cron/crontabs

# This runs cron in the foreground with loglevel 2
CMD [ "crond", "-l", "0", "-f", "-L", "/root/cron.log" ]