# Generated by Django 4.2 on 2023-04-28 16:03

from django.db import migrations, models
import django.db.models.deletion
import feeder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Цвет бэджика',
                'verbose_name_plural': 'Цвета бэджика',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено?')),
                ('daily_amount', models.IntegerField(default=0, verbose_name='Дневное количество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('pin_code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Код авторизации')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухни',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uuid', models.UUIDField(db_index=True, default=feeder.models.gen_uuid, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('nickname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ник')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Фотография')),
                ('position', models.TextField(blank=True, null=True, verbose_name='')),
                ('qr', models.TextField(blank=True, null=True, unique=True, verbose_name='QR-код')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='Активен с ')),
                ('active_to', models.DateTimeField(blank=True, null=True, verbose_name='Активен до')),
                ('arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отъезда')),
                ('daily_eats', models.IntegerField(default=0, verbose_name='Количество приёмов пищи в день')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен?')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован?')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Вегетарианец?')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('color_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='feeder.color', verbose_name='Цвет бэджика')),
                ('department', models.ManyToManyField(to='feeder.department', verbose_name='Департамент')),
                ('feed_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feeder.feedtype', verbose_name='Тип питания')),
                ('kitchen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feeder.kitchen', verbose_name='Кухня')),
                ('location', models.ManyToManyField(to='feeder.location', verbose_name='Локация')),
                ('ref_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeder.volunteer', verbose_name='Связан с ')),
            ],
            options={
                'verbose_name': 'Волонтёр',
                'verbose_name_plural': 'Волонтёры',
            },
        ),
        migrations.CreateModel(
            name='FeedTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ulid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('dtime', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feeder.kitchen', verbose_name='Кухня')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeder.volunteer', verbose_name='Волонтёр')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_leader', to='feeder.volunteer', verbose_name='Лидер'),
        ),
    ]
