# Generated by Django 4.2 on 2023-05-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='department',
            new_name='departments',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='location',
            new_name='locations',
        ),
        migrations.AlterField(
            model_name='feedtransaction',
            name='dtime',
            field=models.DateTimeField(),
        ),
    ]
