# Generated by Django 4.2.1 on 2023-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_rename_department_volunteer_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
