# Generated by Django 4.2.1 on 2023-05-14 10:08

from django.db import migrations, models
import feeder.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0003_volunteer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtransaction',
            name='meal_time',
            field=models.TextField(default='breakfast', max_length=10, validators=[feeder.models.validate_meal_time], verbose_name='Время питания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
    ]
