# Generated by Django 4.2.1 on 2023-05-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0004_feedtransaction_meal_time_volunteer_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='locations',
        ),
    ]
