# Generated by Django 4.2.1 on 2023-05-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0005_remove_volunteer_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtransaction',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Вегетарианец?'),
            preserve_default=False,
        ),
    ]
